[program:hg]
command=/app/hg -email leenchan@gmail.com -pass r5scx8nPAJZrFt -device %DEVICE_NAME% -tou-accept
directory=/app
autostart=true
autorestart=true
startretries=3
stderr_logfile=/var/log/hg.err.log
stdout_logfile=/var/log/hg.out.log
user=root
environment=DOTNET_SYSTEM_GLOBALIZATION_INVARIANT="0"
