[program:ws]
command=/usr/local/bin/node ws.js
directory=/app
autostart=true
autorestart=true
startretries=3
stderr_logfile=/var/log/ws.err.log
stdout_logfile=/var/log/ws.out.log
user=root
environment=PORT=%PORT_WS%