[program:pc]
command=/app/pc -email=leenchan@gmail.com -password=r5scx8nPAJZrFt -device-name=%DEVICE_NAME% -device-id=%DEVICE_NAME% -accept-tos
directory=/app
autostart=true
autorestart=true
startretries=3
stderr_logfile=/var/log/pc.err.log
stdout_logfile=/var/log/pc.out.log
user=root
environment=DOTNET_SYSTEM_GLOBALIZATION_INVARIANT="0"
